#ifndef USER_CONSTANTS_H
#define USER_CONSTANTS_H

// ASEGURARSE QUE PPR SEA PAR YA QUE AL CONFIGURAR ENCODER SE DIVIDE POR 2 PORQUE EL TIMER CUENTA FLANCO DE SUBIDA Y DE BAJADA
#define ENCODER_PPR 2000

#endif //USER_CONSTANTS_H
